### ISSUE TITLE
Invalid compression service address

### ISSUE THREAD

**Issue by fmanrique96** [himshim/bandwidth-hero-proxy2#22]
### Details

I deploy to Netlify, zero issues in deploying, go to copy and paste link in extension and I get "Invalid compression service address
Given URL does not appear to be running Bandwidth Hero data compression service." each time, tried changing the URL for small things and nothing works. The site is up and says:

"Bandwidth Hero Proxy
Welcome to the Bandwidth Hero Proxy!

To use the proxy in the Bandwidth Hero extension, follow these steps:

Open the Bandwidth Hero extension settings.
In the Data Compression Service section, add the following URL: https://your-netlify-domain.netlify.app/api/index.
Save the settings and you are good to go!
For more information and the source code, visit the [GitHub repository](https://github.com/himshim/bandwidth-hero-proxy2)."

but I copy and paste this link into the extension and add /api/index. and nothing

<details open>
<summary>Checklist</summary>

- [X] Modify `functions/index.js` ✓ https://github.com/himshim/bandwidth-hero-proxy2/commit/af96ddf3f6b48d90ee8ba4263a2ef16230f52506
- [X] Check `functions/index.js` ✓ https://github.com/himshim/bandwidth-hero-proxy2/commit/4d59b89a80fcfd913f0760b50e8a8e376b3831eb

![Flowchart](http://24.199.78.105:8082/public/e2970a14e7cbb05ff589132a82aab7b29157e8484fbbc14de7081e33ab700930_22_flowchart.svg)
</details>

**Comment by amkazan** [comment]
anybody here?

**Comment by kilomeetrics** [comment]
same here! Doesn't working.  Help pls! Someone?

**Comment by amkazan** [comment]
@kilomeetrics 
> same here! Doesn't working. Help pls! Someone?

go to chrome plugin page, i left comment with date, other service worked for me

**Comment by kilomeetrics** [comment]
> @kilomeetrics
> 
> > same here! Doesn't working. Help pls! Someone?
> 
> go to chrome plugin page, i left comment with date, other service worked for me

I search "chrome plugin page" in google (because I have no idea what you mean) and the first results is the google web store. Maybe you mean that i must be use google chrome and install the addon from there? Then itsn't worth it, because google chrome had an inbuilt compression machine with the google proxy.

**Comment by SAOS200X** [comment]
any solution?
